[project]
name = "k12diag"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Tommy Liu", email = "tommyyliu@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
    "pyarrow>=25.0.1",
    "scikit-learn>=1.9.1",
    "scipy>=1.18.1",
    "torch>=2.14.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
